const rawPortfolioItems  = [
  // {
  //   id: 1,
  //   image: '/zouitina/201.jpg',
  //   title: 'ZOUITINA GAMME VERRE',
  //   subtitle: 'Interior',
  //   webImage: '/zouitina/163.png',
  //   categories: ['Packaging', 'Print'],
  //   classement: "9",
  //   thumbnail: '/zouitina/133.png',
  //   solutions: "Design of refined promotional visuals, combining aesthetics and readability, to create a distinctive graphic universe and strengthen the brand’s impact on visitors.",
  //   challenge: "Highlight Zouitina’s glass range in a highly competitive environment, attracting attention while asserting a premium identity.",
  //   description: "Creation of glass and PET packaging for the range of olive oils and olives",
  //   photos: [       
  //     "/zouitina/200.jpg",
  //     "/zouitina/201.jpg",
  //     ]
  // },
  {
    id: 2,
    image: '/eni/005.jpg',
    title: 'ENI GROUP',
    webImage: '/eni/152.png',
    subtitle: 'Brand Identity',
    classement: "5",
    thumbnail:  '/eni/56.png',
    solutions: "Create a strong and distinctive identity for a major player in temporary work and related services, capable of conveying its expertise, reliability, and market positioning.",
    challenge: "Development of a modern and coherent graphic charter, applied across all print and digital media, accompanied by a global communication strategy. A framework designed to affirm ENI Group’s credibility, strengthen its brand awareness, and unite its diverse audiences.",

    categories: ['Print'],
    photos: [       
        "/eni/51.png",
        "/eni/52.png",
        "/eni/53.png",
        "/eni/56.png",
        "/eni/57.png",
        "/eni/58.png",
        "/eni/59.png",
        "/eni/54.png",
        "/eni/55.png",
        "/eni/152.png",
        "/eni/167.png",
        "/eni/168.png",
        "/eni/46.png",
        "/eni/47.png",
        "/eni/48.png",
        "/eni/49.png",
        "/eni/011.png",
        "/eni/012.png",
        "/eni/46.png",
        "/eni/013.png",
        "/eni/014.png",
      ],
    description: "Creation of visual identity and global communication strategy (print, web, and social media) for a major group in temporary work and associated services."
  },
  {
    id: 3,
    image: '/casabussines/43.png',
    title: 'CASA BUSINESS TOWERS',
    subtitle: 'PRINT',
    challenge: "Design signage that matches the scale of the Casa Business Towers project: combining clarity, elegance, and innovation to provide a smooth experience for visitors and residents alike.",
    thumbnail: '/casabussines/46.jpg',
    solutions: "A harmonious system, combining print and digital media, conceived as a coherent visual journey. Signage that goes beyond simple orientation to become a symbol of image and prestige.",
    categories: ['Print'],
    photos: [       
        "/casabussines/42.png",
        "/casabussines/45.png",
        "/casabussines/44.png",
        "/casabussines/43.png",
        "/casabussines/46.jpg",
      ],
    description: "Design of the complete signage system in print and digital formats for the Casa Business Towers project"
  },
  {
    id: 4,
    image: '/lito/121.png',
    title: 'LITO',
    subtitle: 'Packaging',
    categories: ['Packaging'],
    challenge: "Position a sardine brand in a competitive market by balancing authenticity, attractiveness, and international distribution standards.",
    thumbnail: '/lito/121.png',
    solutions: "A distinctive logo and carefully crafted packaging, blending modernity and culinary heritage, designed to appeal to European consumers and highlight the brand’s origin.",
    photos: [       
        "/lito/121.png",
        "/lito/122.png",
        "/lito/123.png",
      ],
    description: "Creation of logo + packaging for a sardine brand marketed in Europe"
  },
  {
    id: 6,
    image: '/64.png',
    title: 'UM6P/LIMSET',
    subtitle: 'Scientific Report',
    classement: "2",
    challenge: "Showcase the work of a UM6P subsidiary through a rigorous scientific document that combines academic precision, clarity, and visual appeal.",
    thumbnail: '/64.png',
    solutions: "A report designed as a reference tool, combining editorial accuracy, clean design, and graphic consistency, reflecting the seriousness and excellence of UM6P/LIMSET.",
    categories: ['Print'],
    photos: [       
        "/64.png",
        "/65.png",
        "/67.png",
        "/68.png",
      ],
    description: "Design and execution of a scientific report for a UM6P subsidiary"
  },
  {
    id: 7,
    image: '/5.png',
    title: 'NUANCES DE GRIS',
    subtitle: 'Brand strategy',
    challenge: "Give a strong and distinctive identity to a concrete panel brand, transforming a raw material into a visual universe of aesthetics and modernity.",
    thumbnail: '/5.png',
    solutions: "A sober and contemporary visual identity, inspired by the material itself, conveying robustness, reliability, and architectural design.",
    categories: ['Brand strategy', 'Audiovisual Production', 'Operational'],
    photos: [       
        "/1.png",
        "/2.png",
        "/3.png",
        "/4.png",
        "/5.png",
        "/6.png",
      ],
    description: "Creation of a visual identity for a concrete panel brand."
  },
  {
    id: 8,
    image: '/7.png',
    title: 'VITA ART FLORAL',
    subtitle: 'Brand strategy',
    challenge: "Reinvent the image of a leading Moroccan floral art brand, enhancing its heritage while anchoring it in a contemporary aesthetic.",
    thumbnail: '/7.png',
    solutions: "A complete rebranding, blending elegance and modernity, to express the refined universe of Vita Art Floral, strengthen its premium positioning, and attract a demanding clientele.",
    categories: ['Brand strategy', 'Operational'],
    photos: [       
        "/7.png",
        "/8.png",
        "/9.png",
        "/10.png",
        "/11.png",
        "/12.png",
      ],
    description: "Complete rebranding of a leading Moroccan floral art brand"
  },
  {
    id: 9,
    image: '/20.png',
    title: 'CAVIAR & CO | VISUAL IDENTITY',
    challenge: "Express the refinement of a caviar and fine products house.",
    thumbnail:'/20.png',
    solutions: "An elegant and sophisticated identity, reflecting luxury and exclusivity.",
    subtitle: 'Brand strategy',
    categories: ['Brand strategy', 'Operational', 'Audiovisual Production'],
    photos: [       
         "/21.png",
        "/22.png",
        "/20.png",
      ],
    description: "Creation of a visual identity for a caviar and fine products house."
  },
  {
    id: 10,
    image: '/15.png',
    title: 'CONAGRO | NEW VISUAL IDENTITY CREATION',
    subtitle: 'Multi-service',
    challenge: "Create a distinctive identity for a Moroccan agro-industry player.",
    thumbnail: '/15.png',
    solutions: "A strong visual identity, reflecting expertise and industry anchoring.",
    categories: ['Audiovisual Production', 'Print', 'Brand strategy'],
    photos: [
        "/13.png",
        "/14.png",
        "/15.png",
        "/16.png",
        "/17.png",
        "/18.png",
      ],
    description: "Creation of visual identity for a Moroccan agro-industry player"
  },
  {
    id: 11,
    image: '/119.png',
    title: 'SHAJARA FRUITS',
    subtitle: 'Packaging',
    challenge: "Develop distinctive packaging for the red fruits range, combining freshness and commercial appeal.",
    thumbnail: '/119.png',
    solutions: "Bright and modern designs, highlighting naturalness and Moroccan identity of the brand.",
    categories: ['Packaging'],
    photos: [
        "/119.png",
      ],
    description: "Creation of packaging for the Shajara red fruits range"
  },
  {
    id: 12,
    image: '/24.png',
    title: 'SHAPE AND SHADE',
    subtitle: 'Brand Identity',
    classement: "6",
    challenge: "Redefine the image of a brand specialized in concrete design.",
    thumbnail: '/24.png',
    solutions: "A complete rebranding, combining modernity, minimalism, and architectural elegance.",
    categories: ['Brand strategy'],
    photos: [ 
        "shape.gif",
        // "25.png",
        // "26.png",
        // "27.png",
      ],
    description: "Complete rebranding of a Moroccan brand specialized in concrete design"
  },
  {
    id: 14,
    image: '/92.png',
    title: 'LE CARROUSEL',
    challenge: "Highlight a luxury real estate project for a demanding clientele.",
    thumbnail: '/92.png',
    solutions: "A refined and elegant brochure, designed as an editorial showcase reflecting prestige and exclusivity.",
    subtitle: 'Print',
    categories: ['Print'],
    photos: [
        "/92.png",
        "/93.png",
        "/94.png",
        "/95.png",
        "/96.png",
        "/97.png",
      ],
    description: "Brochure – Luxury real estate communication – Premium supports"
  },
  {
    id: 15,
    image: '/89.png',
    title: 'ESCA',
    challenge: "Highlight a luxury real estate project for a demanding clientele.",
    thumbnail: '/89.png',
    solutions: "A refined and elegant brochure, designed as an editorial showcase reflecting prestige and exclusivity.",
    subtitle: 'Print',
    categories: ['Print'],
    photos: [       
       "/87.png",
       "/88.png",
       "/89.png",
       "/90.png",
       "/91.png",
      ],
    description: "4x3 outdoor campaign with multiple visuals for the launch of the new ESCA campus"
  },
  {
    id: 17,
    image: '/72.png',
    title: 'UM6P/OCP',
    challenge: "Give a strong visual identity to an event bringing together OCP, UM6P, and AFA.",
    thumbnail: '/71.png',
    solutions: "An impactful key visual and a carefully designed brochure, reflecting the scope and prestige of the event.",
    subtitle: 'Event keyvisual',
    classement: "3",
    categories: ['Print'],
    photos: [       
      "71.png",
      "72.png",
      ],
    description: "Design of key visual + brochure for an event organized by OCP, UM6P, and AFA"
  },
  {
    id: 19,
    image: '/31.png',
    title: "JEAN MICHEL MUSIA",
     classement: "7",
    subtitle: 'Brand strategy',
    challenge: "Launch a new bakery brand in Morocco with a distinctive identity.",
    thumbnail: '/31.png',
    solutions: "Creation of a refined brand universe, combining artisanal tradition and modernity.",
    categories: ['Brand strategy'],
    photos: [       
         "/30.png",
         "/29.png",
         "/34.png",
         "/31.png",
        "/33.png",
        "/32.png",
      ],
    description: "Brand creation for a new bakery chain in Morocco"
  },
  {
    id: 21,
    thumbnail: "provi.png",
    image: "/videos/providence.mp4",
    title: "PROVIDENCE VERTE CORPORATE FILM",
    subtitle: 'Corporate film',
    classement: "4",
    categories: ['Production vidéo'],
    description: "Shooting and production of a corporate film for Providence Verte",
    
    videos: [
      {
        src: "https://www.youtube.com/watch?v=QQFesYmphoY",
        thumbnail: "zouitina/134.png",
      },
    ],
    type: 'video'
  },
  {
    id: 22,
    thumbnail: "zouitina/zouitina.JPG",
    image: "/videos/zouitinaa.mp4",
    title: "ZOUITINA CORPORATE FILM",
    subtitle: 'Video Production',
    categories: ['Production vidéo'],
    description: "Shooting and production of a corporate film for Zouitina",
    
    videos: [
      {
        src: "https://www.youtube.com/watch?v=XhFUS9-uyuQ&t=9s",
        thumbnail: "zouitina/134.png",
      },
      {
        src: "https://drive.google.com/file/d/14BpWYP2aGJJ2FL0RIh4Td1bGaDDewbUR/view",
        thumbnail: "zouitina/134.png",
      },
    ],
    type: 'video'
  },
  {
    id: 25,
    thumbnail: "csdm.JPG",
    image: "/videos/csdm.mp4",
    title: "UM6P/DEO",
    subtitle: 'Video Production',
    categories: ['Production vidéo'],
    classement: "1",
    description: "Presentation videos of the DEO/UM6P departments for the Digital Day event",
    
    videos: [
      {
        src: "https://www.youtube.com/watch?v=XOLpb8veQLE",
        thumbnail: "csdm.JPG",
      },
      {
        src: "https://drive.google.com/file/d/1CrLr_wLFHJuNIUp-edXSR4iY0Oo-DGem/view",
        thumbnail: "csdm.JPG",
      },
      {
        src: "https://drive.google.com/file/d/1B0VKq-VBWoR85WQLoN-WbJFOW1g1Q6Pi/view",
        thumbnail: "csdm.JPG",
      },
      {
        src: "https://drive.google.com/file/d/1OW6uvEQjFQID9gXDlgQsntnx_lugiUWD/view",
        thumbnail: "csdm.JPG",
      },
      {
        src: "https://drive.google.com/file/d/1WVOmp26MLwXzOl-arJBKC1JG4I6543FK/view",
        thumbnail: "csdm.JPG",
      },
    ],
    type: 'video'
  },
  {
    id: 29,
    image: '/zouitina/006.jpg',
    title: 'ZOUITINA OLIVE OIL',
    subtitle: 'Brand Packaging',
    webImage: '/zouitina/163.png',
    thumbnail: '/zouitina/004.png',
    solutions: "Design of refined promotional visuals, combining aesthetics and readability, to create a distinctive graphic universe and strengthen the brand’s impact on visitors.",
    challenge: "Highlight Zouitina’s glass range in a highly competitive environment, attracting attention while asserting a premium identity.",
    categories: ['Brand strategy'],
    classement: "5",
    description: "Booth design – Promotional visuals – Agricultural fairs",
    photos: [       
          "/zouitina/004.png",
          "/zouitina/00.png",
          "/zouitina/003.png",
          "/zouitina/000.png",
        ]
  },
  {
    id: 30,
    image: '/zouitina/118.png',
    title: 'ZOUITINA',
    subtitle: 'Social Content Videos',
    thumbnail: '/zouitina/133.png',
    solutions: "Production of a series of video capsules and creation of a corporate film reflecting the universe and quality of the brand.",
    challenge: "Create inspiring and immersive digital content capable of strengthening consumer engagement.",
    webImage: '/zouitina/163.png',
    categories: ['Brand strategy'],
   
    description: "Recipe capsules – Corporate film – Social media",
    photos: [       
        "/zouitina/148.png",
        "/zouitina/144.png",
        "/zouitina/145.png",
        "/111.JPG",
        "/zouitina/181.png",
        "/zouitina/183.png",
        "/zouitina/147.png",
        "/zouitina/130.png",
      ]
  },
];

export const portfolioItems = rawPortfolioItems.map((item, index) => ({
  ...item,
  id: index + 1,
}));
